apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "eduvize.fullname" . }}-postgres"
  namespace: {{ .Release.Namespace }}
  labels: 
    {{ include "eduvize.labels" . | nindent 4 }}
spec:
  replicas:  {{ .Values.database.replicas }}
  selector:
    matchLabels:
      app: "{{ include "eduvize.fullname" . }}-postgres"
      {{- include "eduvize.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: "{{ include "eduvize.fullname" . }}-postgres"
        {{- include "eduvize.labels" . | nindent 8 }}
    spec:
      {{- if .Values.privateRegistry.enabled }}
      imagePullSecrets:
        - name: {{ .Values.privateRegistry.secretName }}
      {{- end }}
      containers:
        - name: "{{ include "eduvize.fullname" . }}-postgres"
          image: {{ .Values.database.image }}
          ports:
            - containerPort: {{ .Values.database.port }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.database.name }}
            - name: POSTGRES_USER
              value: {{ .Values.database.user }}
            {{- range .Values.database.envSecretMap }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: {{ .secret }}
                  key: {{ .key }}
            {{- end}}
          volumeMounts:
            - name: "{{ include "eduvize.fullname" . }}-postgres-volume"
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: "{{ include "eduvize.fullname" . }}-postgres-volume"
          persistentVolumeClaim:
            claimName: "{{ include "eduvize.fullname" . }}-postgres-pvc"