apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eduvize.fullname" . }}-redis
  labels:
    {{- include "eduvize.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas.redis }}
  selector:
    matchLabels:
      app: "{{ include "eduvize.fullname" . }}-redis"
      {{- include "eduvize.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: "{{ include "eduvize.fullname" . }}-redis"
        {{- include "eduvize.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "eduvize.name" . }}-redis
          image: {{ .Values.image.redis }}
          ports:
            - containerPort: {{ .Values.ports.redis }}