image:
  app: registry.crosswinds.cloud/eduvize/app:latest
  api: registry.crosswinds.cloud/eduvize/api:latest
  redis: redis:6
  postgres: postgres:13
  s3: docker.io/bitnami/minio:2024

ports:
  app: 8000
  api: 8000
  redis: 6379
  postgres: 5432
  s3:
    http: 9000
    console: 9001

replicas:
  app: 1
  api: 1
  redis: 1
  postgres: 1
  s3: 1

ingress:
  enabled: true
  hostname: eduvize.dev
  ingressClassName: public
  tls:
    enabled: true
    secretName: eduvize-tls-secret
    clusterIssuer: letsencrypt-prod

database:
  name: eduvize
  size: 10Gi

storage:
  bucketName: eduvize
  region: us-east-1
  size: 10Gi

environment:
  api:
    - name: PUBLIC_UI_URL
      value: https://eduvize.dev
    - name: PUBLIC_URL
      value: https://api.eduvize.dev/api
    - name: DASHBOARD_ENDPOINT
      value: dashboard
    - name: SES_CONFIGURATION_SET
      value: main-config
    - name: SES_REGION
      value: us-east-2
    - name: NOREPLY_ADDRESS
      value: no-reply@mail.eduvize.dev

secretEnvironmentBlock:
  api:
    - name: AWS_ACCESS_KEY
      secret: aws
      key: access-key
    - name: AWS_SECRET_KEY
      secret: aws
      key: secret-key
    - name: POSTGRES_USER
      secret: postgres
      key: username
    - name: POSTGRES_PASSWORD
      secret: postgres
      key: password
    - name: S3_ACCESS_KEY
      secret: s3
      key: root-user
    - name: S3_SECRET_KEY
      secret: s3
      key: root-password
    - name: OPENAI_KEY
      secret: openai
      key: api-key
  postgres:
    - name: POSTGRES_USER
      secret: postgres
      key: username
    - name: POSTGRES_PASSWORD
      secret: postgres
      key: password
  s3:
    - name: MINIO_ROOT_USER
      secret: s3
      key: root-user
    - name: MINIO_ROOT_PASSWORD
      secret: s3
      key: root-password

persistence:
  storageClass: microk8s-hostpath

privateRegistry:
  enabled: true
  secretName: regcred