apiVersion: v1
kind: Service
metadata:
  name: "{{ include "eduvize.fullname" . }}-api-service"
  namespace: {{ .Release.Namespace }}
  labels: 
    {{- include "eduvize.labels" . | nindent 4 }}
spec:
  selector:
    app: "{{ include "eduvize.fullname" . }}-api"
  ports:
    - protocol: TCP
      port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}