apiVersion: v1
kind: Service
metadata:
  name: "{{ include "eduvize.fullname" . }}-service"
  labels: 
    {{- include "eduvize.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "eduvize.fullname" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.ports.app }}
      targetPort: {{ .Values.ports.app }}