apiVersion: v1
kind: Service
metadata:
  name: "{{ include "eduvize.fullname" . }}-redis-service"
  namespace: {{ .Release.Namespace }}
  labels: 
    {{- include "eduvize.labels" . | nindent 4 }}
spec:
  selector:
    app: "{{ include "eduvize.fullname" . }}-redis"
  ports:
    - protocol: TCP
      port: {{ .Values.redis.port }}
      targetPort: {{ .Values.redis.port }}