apiVersion: v1
kind: Service
metadata:
  name: "{{ include "eduvize.fullname" . }}-s3-service"
  namespace: {{ .Release.Namespace }}
  labels: 
    {{- include "eduvize.labels" . | nindent 4 }}
spec:
  selector:
    app: "{{ include "eduvize.fullname" . }}-s3"
  ports:
    - protocol: TCP
      name: http
      port: {{ .Values.storage.ports.http }}
      targetPort: {{ .Values.storage.ports.http }}
    - protocol: TCP
      name: console
      port: {{ .Values.storage.ports.console }}
      targetPort: {{ .Values.storage.ports.console }}