apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "eduvize.fullname" . }}-s3-pvc"
  labels: 
    {{- include "eduvize.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}