apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: playground-orchestrator-binding
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: playground-orchestrator-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: playground-orchestrator
  apiGroup: rbac.authorization.k8s.io
