version: "3.8"

services:
  api:
    build: .
    ports:
      - "8000:80"
    environment:
      - PORT=80
      - POSTGRES_HOST=database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=devpassword
      - POSTGRES_DB=eduvize
      - S3_ENDPOINT=http://s3:9000
      - S3_PUBLIC_ENDPOINT=http://localhost:9000
      - S3_ACCESS_KEY=minio
      - S3_SECRET_KEY=minio123
      - S3_BUCKET=eduvize
    depends_on:
      - database
      - redis
      - s3
    networks:
      - app-tier

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-tier

  database:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=devpassword
      - POSTGRES_DB=eduvize
    volumes:
      - ./scripts/database/seed_dev_environment.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

    networks:
      - app-tier

  s3:
    image: docker.io/bitnami/minio:2024
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
      - MINIO_DEFAULT_BUCKETS=eduvize:public
      - MINIO_REGION=us-east-1
    volumes:
      - s3_data:/data
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge

volumes:
  postgres_data:
  s3_data:
