name: Client Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/client/**"
      - "kubernetes/eduvize/templates/deployments/app-*.yaml"
      - "kubernetes/eduvize/templates/ingress/app-*.yaml"
      - "kubernetes/eduvize/templates/services/app-*.yaml"

jobs:
  deploy-client:
    uses: ./.github/workflows/reusable_build_deploy.yml
    with:
      IMAGE_NAME: "app"
      DOCKERFILE: "src/client/Dockerfile"
      BUILD_CONTEXT: "src/client"
    secrets: inherit
