name: Trigger Client Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/client/**"
      - "kubernetes/eduvize/templates/deployments/app-*.yaml"
      - "kubernetes/eduvize/templates/ingress/app-*.yaml"
      - "kubernetes/eduvize/templates/services/app-*.yaml"

jobs:
  deploy-client:
    uses: ./.github/workflows/reusable_build_deploy.yml
    with:
      image_name: "app"
      dockerfile: "src/client/Dockerfile"
      build_context: "src/client"
      domain_name: "eduvize.dev"
    secrets: inherit
