# File: .github/workflows/trigger-client-deployment.yml

name: Trigger Client Deployment

on:
  push:
    branches:
      - main
    paths:
      - "src/client/**"
      - "kubernetes/eduvize/templates/deployments/app-*.yaml"
      - "kubernetes/eduvize/templates/ingress/app-*.yaml"
      - "kubernetes/eduvize/templates/services/app-*.yaml"

jobs:
  deploy-client:
    uses: ./.github/workflows/build_deploy.yml
    with:
      image_name: "app"
      dockerfile: "src/client/Dockerfile"
      build_context: "src/client"
      registry_prefix: "eduvize"
      domain_name: ${{ secrets.DOMAIN_NAME }}
      release_namespace: ${{ secrets.RELEASE_NAMESPACE }}
    secrets:
      registry_name: ${{ secrets.REGISTRY_NAME }}
      registry_username: ${{ secrets.REGISTRY_USERNAME }}
      registry_password: ${{ secrets.REGISTRY_PASSWORD }}
      kubeconfig_data: ${{ secrets.KUBECONFIG_DATA }}
