name: Trigger Client Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/client/**"
      - "kubernetes/eduvize/templates/deployments/app-*.yaml"
      - "kubernetes/eduvize/templates/ingress/app-*.yaml"
      - "kubernetes/eduvize/templates/services/app-*.yaml"

env:
  REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}
  REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
  DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
  RELEASE_NAMESPACE: ${{ secrets.RELEASE_NAMESPACE || 'eduvize' }}
  KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_DATA }}

jobs:
  deploy-client:
    uses: ./.github/workflows/reusable_build_deploy.yml
    with:
      image_name: "app"
      dockerfile: "src/client/Dockerfile"
      build_context: "src/client"
      registry_prefix: "eduvize"
      domain_name: ${{ env.DOMAIN_NAME }}
    secrets: inherit
